[2024-09-11T03:27:39.065+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T03:27:39.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-09-11T03:27:39.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-09-11T03:27:39.104+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-11T03:27:39.130+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-07-13 00:00:00+00:00
[2024-09-11T03:27:39.139+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=24548) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T03:27:39.140+0000] {standard_task_runner.py:63} INFO - Started process 24565 to run task
[2024-09-11T03:27:39.139+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'scheduled__2024-07-13T00:00:00+00:00', '--job-id', '4238', '--raw', '--subdir', 'DAGS_FOLDER/16_dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpx1xju90a']
[2024-09-11T03:27:39.141+0000] {standard_task_runner.py:91} INFO - Job 4238: Subtask sensor_minio_s3
[2024-09-11T03:27:39.188+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2024-07-13T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T03:27:39.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='dag_with_minio_s3_v04' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-13T00:00:00+00:00'
[2024-09-11T03:27:39.315+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T03:27:39.340+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-09-11T03:27:39.341+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-09-11T03:27:39.355+0000] {base.py:84} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2024-09-11T03:27:39.383+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-09-11T03:27:39.818+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-09-11T03:27:39.818+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T03:27:39.831+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_minio_s3_v04, task_id=sensor_minio_s3, run_id=scheduled__2024-07-13T00:00:00+00:00, execution_date=20240713T000000, start_date=20240911T032739, end_date=20240911T032739
[2024-09-11T03:27:39.877+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T03:27:39.894+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T03:27:39.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
