[2024-09-11T03:24:43.733+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T03:24:43.748+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-09-11T03:24:43.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-09-11T03:24:43.756+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T03:24:43.772+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-08-07 00:00:00+00:00
[2024-09-11T03:24:43.779+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=24121) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T03:24:43.780+0000] {standard_task_runner.py:63} INFO - Started process 24124 to run task
[2024-09-11T03:24:43.779+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'scheduled__2024-08-07T00:00:00+00:00', '--job-id', '4192', '--raw', '--subdir', 'DAGS_FOLDER/16_dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpvuys4six']
[2024-09-11T03:24:43.780+0000] {standard_task_runner.py:91} INFO - Job 4192: Subtask sensor_minio_s3
[2024-09-11T03:24:43.822+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2024-08-07T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T03:24:43.912+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='dag_with_minio_s3_v04' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-07T00:00:00+00:00'
[2024-09-11T03:24:43.913+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T03:24:43.927+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-09-11T03:24:43.928+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-09-11T03:24:43.935+0000] {base.py:84} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2024-09-11T03:24:43.936+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-09-11T03:24:44.223+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-09-11T03:24:44.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T03:24:44.232+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_minio_s3_v04, task_id=sensor_minio_s3, run_id=scheduled__2024-08-07T00:00:00+00:00, execution_date=20240807T000000, start_date=20240911T032443, end_date=20240911T032444
[2024-09-11T03:24:44.274+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T03:24:44.289+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T03:24:44.294+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
