[2024-07-02T03:53:15.802+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T03:53:15.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgers_hooks_v01.postgres_to_s3 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T03:53:15.841+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgers_hooks_v01.postgres_to_s3 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T03:53:15.842+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-07-02T03:53:15.856+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-01 00:00:00+00:00
[2024-07-02T03:53:15.863+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgers_hooks_v01', 'postgres_to_s3', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_hook.py', '--cfg-path', '/tmp/tmp4d010m7d']
[2024-07-02T03:53:15.865+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask postgres_to_s3
[2024-07-02T03:53:15.866+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16387) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T03:53:15.866+0000] {standard_task_runner.py:63} INFO - Started process 16388 to run task
[2024-07-02T03:53:15.904+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgers_hooks_v01.postgres_to_s3 scheduled__2024-07-01T00:00:00+00:00 [running]> on host 468cd84e5e4e
[2024-07-02T03:53:15.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='dag_with_postgers_hooks_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T03:53:15.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T03:53:15.992+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T03:53:15.993+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_postgress_hook.py", line 21, in postgres_to_s3
    hook = PostgressHook(postgres_conn_id="postgres_conn_id")
           ^^^^^^^^^^^^^
NameError: name 'PostgressHook' is not defined. Did you mean: 'PostgresHook'?
[2024-07-02T03:53:16.002+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgers_hooks_v01, task_id=postgres_to_s3, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20240702T035315, end_date=20240702T035316
[2024-07-02T03:53:16.014+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task postgres_to_s3 (name 'PostgressHook' is not defined; 16388)
[2024-07-02T03:53:16.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T03:53:16.054+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T03:53:16.057+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
