[2024-07-05T05:14:11.498+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T05:14:11.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ml_pipeline_docker_operator_v01.docker_model_train_and_publish_task_v01 manual__2024-07-05T05:14:09.627485+00:00 [queued]>
[2024-07-05T05:14:11.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ml_pipeline_docker_operator_v01.docker_model_train_and_publish_task_v01 manual__2024-07-05T05:14:09.627485+00:00 [queued]>
[2024-07-05T05:14:11.537+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-05T05:14:11.553+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): docker_model_train_and_publish_task_v01> on 2024-07-05 05:14:09.627485+00:00
[2024-07-05T05:14:11.560+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ml_pipeline_docker_operator_v01', 'docker_model_train_and_publish_task_v01', 'manual__2024-07-05T05:14:09.627485+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_with_docker_operator.py', '--cfg-path', '/tmp/tmp_k_die6l']
[2024-07-05T05:14:11.561+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask docker_model_train_and_publish_task_v01
[2024-07-05T05:14:11.563+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-05T05:14:11.563+0000] {standard_task_runner.py:63} INFO - Started process 301 to run task
[2024-07-05T05:14:11.601+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ml_pipeline_docker_operator_v01.docker_model_train_and_publish_task_v01 manual__2024-07-05T05:14:09.627485+00:00 [running]> on host 339cc03d645e
[2024-07-05T05:14:11.682+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_ml_pipeline_docker_operator_v01' AIRFLOW_CTX_TASK_ID='docker_model_train_and_publish_task_v01' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T05:14:09.627485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T05:14:09.627485+00:00'
[2024-07-05T05:14:11.683+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T05:14:11.721+0000] {docker.py:366} INFO - Starting docker container from image regression-training-image:v1.0
[2024-07-05T05:14:12.300+0000] {docker.py:436} INFO - python: can't open file '/app/model_tuning.py': [Errno 2] No such file or directory
[2024-07-05T05:14:12.788+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T05:14:12.797+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2024-07-05T05:14:12.801+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ml_pipeline_docker_operator_v01, task_id=docker_model_train_and_publish_task_v01, run_id=manual__2024-07-05T05:14:09.627485+00:00, execution_date=20240705T051409, start_date=20240705T051411, end_date=20240705T051412
[2024-07-05T05:14:12.816+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task docker_model_train_and_publish_task_v01 (Docker container failed: {'StatusCode': 2}; 301)
[2024-07-05T05:14:12.860+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-05T05:14:12.875+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T05:14:12.884+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
